#!/bin/bash


if [ -z $1 ]; then
  echo "command: aar <build number>"
  exit 1
fi


version=$1

flutter clean
flutter pub get
flutter build aar --no-release --no-profile --build-number $version

if [ $? -eq 0 ]; then
  echo "打包成功!"
else
  echo "打包失败!"
  exit 1
fi

cp -r -f build/host/outputs/repo/*  ~/.m2/repository

package=$(niet flutter.module.androidPackage pubspec.yaml)

echo "
  repositories {
      mavenLocal()
  }

  dependencies {
     debugImplementation '$package:flutter_debug:$version'
  }
  "